<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-12-12T17:55:30Z" name="Default suite" finished-at="2018-12-12T17:55:34Z" duration-ms="4237">
    <groups>
    </groups>
    <test started-at="2018-12-12T17:55:30Z" name="Default test" finished-at="2018-12-12T17:55:34Z" duration-ms="4237">
      <class name="pomdesign.WebOrderLoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:pomdesign.WebOrderLoginTest@6e509ffa]" started-at="2018-12-12T17:55:30Z" name="setUp" finished-at="2018-12-12T17:55:33Z" duration-ms="3290" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginUsingPOM2()[pri:0, instance:pomdesign.WebOrderLoginTest@6e509ffa]" started-at="2018-12-12T17:55:33Z" name="loginUsingPOM2" finished-at="2018-12-12T17:55:34Z" duration-ms="814" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome, Tester! | Logou] but found [Welcome, Tester! | Logout]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome, Tester! | Logou] but found [Welcome, Tester! | Logout]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pomdesign.WebOrderLoginTest.loginUsingPOM2(WebOrderLoginTest.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUsingPOM2 -->
        <test-method is-config="true" signature="closeUp()[pri:0, instance:pomdesign.WebOrderLoginTest@6e509ffa]" started-at="2018-12-12T17:55:34Z" name="closeUp" finished-at="2018-12-12T17:55:34Z" duration-ms="94" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeUp -->
      </class> <!-- pomdesign.WebOrderLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
